name: Tentative Deploy to shinyapps.io on PR

on:
  pull_request: {}

jobs:
  deploy:
    name: Deploy to shinyapps

    # allow skipping deployment for commits containing '[automated]' or '[no-deploy]' in the commit message
    if: "!contains(github.event.head_commit.message, '[automated]') && !contains(github.event.head_commit.message, '[no-deploy]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        uses: DeeNA95/shinyapps-deploy-github-action@v1.12
        with:
          # account and application name (https://<accountName>.shinyapps.io/<appName>)
          appName: juicedown0
          accountName: kjst

          # token and secret obtained from https://www.shinyapps.io/admin/#/tokens
          accountToken: ${{ secrets.SHINYIO_TOKEN }}
          accountSecret: ${{ secrets.SHINYIO_SECRET }}
          forceUpdate: true

